xcopy Part_V\Chapter_II\100 Part_VI\Chapter_III\189 /s /e /h
xcopy Part_V\Chapter_II\101 Part_VI\Chapter_III\190 /s /e /h
xcopy Part_V\Chapter_II\102 Part_VI\Chapter_III\191 /s /e /h
xcopy Part_V\Chapter_II\103 Part_VI\Chapter_III\192 /s /e /h
xcopy Part_V\Chapter_II\104 Part_VI\Chapter_III\193 /s /e /h
xcopy Part_V\Chapter_II\105 Part_VI\Chapter_III\194 /s /e /h
xcopy Part_V\Chapter_II\106 Part_VI\Chapter_III\195 /s /e /h
xcopy Part_V\Chapter_II\107 Part_VI\Chapter_III\196 /s /e /h
xcopy Part_V\Chapter_II\108 Part_VI\Chapter_III\197 /s /e /h
xcopy Part_V\Chapter_II\109 Part_VI\Chapter_III\198 /s /e /h
xcopy Part_V\Chapter_II\110 Part_VI\Chapter_III\199 /s /e /h
xcopy Part_V\Chapter_II\111 Part_VI\Chapter_III\200 /s /e /h
xcopy Part_V\Chapter_II\112 Part_VI\Chapter_III\202 /s /e /h
xcopy Part_V\Chapter_II\113 Part_VI\Chapter_III\203 /s /e /h
xcopy Part_V\Chapter_II\114 Part_VI\Chapter_III\204 /s /e /h
xcopy Part_V\Chapter_II\115 Part_VI\Chapter_III\205 /s /e /h
xcopy Part_V\Chapter_II\116 Part_VI\Chapter_III\206 /s /e /h
xcopy Part_V\Chapter_II\117 Part_VI\Chapter_III\207 /s /e /h
xcopy Part_V\Chapter_II\118 Part_VI\Chapter_III\208 /s /e /h
xcopy Part_V\Chapter_II\119 Part_VI\Chapter_III\209 /s /e /h
xcopy Part_V\Chapter_II\120 Part_VI\Chapter_III\210 /s /e /h
xcopy Part_V\Chapter_II\121 Part_VI\Chapter_III\211 /s /e /h
xcopy Part_V\Chapter_II\122 Part_VI\Chapter_III\212 /s /e /h
