# Site settings

url: 'https://davidboers.github.io'
baseurl: 'IndianConstitution'

defaults:
  -
    scope:
      path: "en/"
    values:
      lang: "en"

  -
    scope:
      path: "en/**/contents.html"
    values:
      title-begin: "Table of Contents"

  -
    scope:
      path: "hi/"
    values:
      lang: "hi"

exclude:
  - README.md